#include "main.h"

/**
 * TEST CODE BRIEF
 *
 * Use PCNT module to count rising edges generated by LEDC module.
 *
 * Functionality of GPIOs used in this example:
 *   - GPIO18 - output pin of a sample 1 Hz pulse generator,
 *   - GPIO4 - pulse input pin,
 *   - GPIO5 - control input pin.
 *
 */
#define PCNT_INPUT_SIG_IO   4  // Pulse Input GPIO
#define PCNT_INPUT_CTRL_IO  5  // Control GPIO HIGH=count up, LOW=count down
#define LEDC_OUTPUT_IO      18 // Output GPIO of a sample 1 Hz pulse generator
#define MEASUREMENT_PERIOD	5 // Measurement period in seconds
#define K_FACTOR			7.5  // Flow sensor K factor


/* Initialize PCNT functions:
 *  - configure and initialize PCNT
 *  - set up the input filter
 */
static void pcnt_init(int unit)
{
    /* Prepare configuration for the PCNT unit */
    pcnt_config_t pcnt_config = {
        // Set PCNT input signal and control GPIOs
        .pulse_gpio_num = PCNT_INPUT_SIG_IO,
        .ctrl_gpio_num = PCNT_INPUT_CTRL_IO,
        .channel = PCNT_CHANNEL_0,
        .unit = unit,
        // What to do on the positive / negative edge of pulse input?
        .pos_mode = PCNT_COUNT_INC,   // Count up on the positive edge
        .neg_mode = PCNT_COUNT_DIS,   // Keep the counter value on the negative edge
        // What to do when control input is low or high?
        .lctrl_mode = PCNT_MODE_REVERSE, // Reverse counting direction if low
        .hctrl_mode = PCNT_MODE_KEEP,    // Keep the primary counter mode if high
    };
    /* Initialize PCNT unit */
    pcnt_unit_config(&pcnt_config);
    /* Configure and enable the input filter */
    pcnt_set_filter_value(unit, 100);
    pcnt_filter_enable(unit);
}

void app_main(void)
{

    gpio_init();
    
    int pcnt_unit = PCNT_UNIT_0;
    int16_t count = 0;
    float flow_rate=0.0;

    /* Initialize PPCNT functions */
    pcnt_init(pcnt_unit);
    pcnt_counter_pause(pcnt_unit);

    printf("Starting...\n");

    //uint32_t adc_value;
    float vwc;

    while(1)
    {
        
        //Clear PCNT's counter 
        pcnt_counter_clear(pcnt_unit);
        pcnt_counter_resume(pcnt_unit);
        //Time delay 
        vTaskDelay(MEASUREMENT_PERIOD*500 / portTICK_PERIOD_MS);
        //Read pulses 
        pcnt_counter_pause(pcnt_unit);
        pcnt_get_counter_value(pcnt_unit, &count);
        printf("Number of pulses: %d in %d seconds\n",count,MEASUREMENT_PERIOD);
        //Calculate flow rate in L/min 
        flow_rate=(float)count/(MEASUREMENT_PERIOD*K_FACTOR);
        printf("Flow rate: %5.2f L/min\n",flow_rate);

        

        /*INICIA CODIGO DE SENSOR DE HUMEDAD*/
        vTaskDelay(500 / portTICK_PERIOD_MS);


        vwc = get_vwc();
        printf("vwc = %f\n", vwc);
        vTaskDelay(500 / portTICK_PERIOD_MS);
    }                                                                                                            
    
}

